import sys

duo_cards = [
    {
        "id": "duo-stockton-malone",
        "name": "Stockton & Malone",
        "subtitle": "Pick and Roll Perfection",
        "team": "Utah Jazz",
        "teamAbbr": "UTA",
        "position": "PG/PF",
        "rarity": "legend",
        "ovr": 94,
        "pts": 21.5,
        "reb": 10.2,
        "ast": 12.8,
        "nbaId": 304,
        "quote": "Pick and Roll Perfection - The most lethal pick-and-roll duo in NBA history."
    },
    {
        "id": "duo-kd-westbrook",
        "name": "KD & Westbrook",
        "subtitle": "Thunder Up",
        "team": "Oklahoma City Thunder",
        "teamAbbr": "OKC",
        "position": "SF/PG",
        "rarity": "franchise",
        "ovr": 93,
        "pts": 29.8,
        "reb": 7.5,
        "ast": 8.2,
        "nbaId": 201142,
        "quote": "Thunder Up - Explosive perimeter scoring and unrelenting athleticism in OKC."
    },
    {
        "id": "duo-lebron-wade",
        "name": "LeBron & Wade",
        "subtitle": "Heatles Backcourt",
        "team": "Miami Heat",
        "teamAbbr": "MIA",
        "position": "SF/SG",
        "rarity": "legend",
        "ovr": 94,
        "pts": 26.8,
        "reb": 7.2,
        "ast": 7.1,
        "nbaId": 2544,
        "quote": "Heatles Backcourt - High-flying fast breaks and championship glory in Miami."
    },
    {
        "id": "duo-magic-kareem",
        "name": "Magic & Kareem",
        "subtitle": "Showtime Connection",
        "team": "Los Angeles Lakers",
        "teamAbbr": "LAL",
        "position": "PG/C",
        "rarity": "legend",
        "ovr": 95,
        "pts": 23.4,
        "reb": 12.1,
        "ast": 12.5,
        "nbaId": 77142,
        "quote": "Showtime Connection - No-look passes and Skyhooks leading to 5 NBA titles."
    },
    {
        "id": "duo-isiah-dumars",
        "name": "Isiah Thomas & Joe Dumars",
        "subtitle": "Bad Boys Backcourt",
        "team": "Detroit Pistons",
        "teamAbbr": "DET",
        "position": "PG/SG",
        "rarity": "franchise",
        "ovr": 90,
        "pts": 19.8,
        "reb": 3.8,
        "ast": 9.2,
        "nbaId": 78318,
        "quote": "Bad Boys Backcourt - Relentless defense and back-to-back championship toughness."
    },
    {
        "id": "duo-jokic-murray",
        "name": "Jokic & Murray",
        "subtitle": "Mile High Connection",
        "team": "Denver Nuggets",
        "teamAbbr": "DEN",
        "position": "C/PG",
        "rarity": "franchise",
        "ovr": 93,
        "pts": 26.1,
        "reb": 11.8,
        "ast": 9.8,
        "nbaId": 203999,
        "quote": "Mile High Connection - Masterful two-man chemistry leading to Denver's first NBA title."
    },
    {
        "id": "duo-cp3-blake",
        "name": "Chris Paul & Blake Griffin",
        "subtitle": "Lob City",
        "team": "LA Clippers",
        "teamAbbr": "LAC",
        "position": "PG/PF",
        "rarity": "allstar",
        "ovr": 89,
        "pts": 20.2,
        "reb": 8.8,
        "ast": 10.4,
        "nbaId": 101108,
        "quote": "Lob City - High-flying alley-oops and electrifying playmaking in LA."
    },
    {
        "id": "duo-luka-kyrie",
        "name": "Luka & Kyrie",
        "subtitle": "Mavs Backcourt",
        "team": "Dallas Mavericks",
        "teamAbbr": "DAL",
        "position": "PG/SG",
        "rarity": "franchise",
        "ovr": 91,
        "pts": 31.2,
        "reb": 8.2,
        "ast": 8.9,
        "nbaId": 1629029,
        "quote": "Mavs Backcourt - Unstoppable isolation scoring and wizardly court vision."
    },
    {
        "id": "duo-bird-mchale",
        "name": "Bird & McHale",
        "subtitle": "Celtics Frontcourt",
        "team": "Boston Celtics",
        "teamAbbr": "BOS",
        "position": "SF/PF",
        "rarity": "legend",
        "ovr": 94,
        "pts": 25.8,
        "reb": 9.8,
        "ast": 6.8,
        "nbaId": 1449,
        "quote": "Celtics Frontcourt - Unmatched footwork, clutch shooting, and 80s Celtics dominance."
    },
    {
        "id": "duo-duncan-robinson",
        "name": "Duncan & David Robinson",
        "subtitle": "Twin Towers",
        "team": "San Antonio Spurs",
        "teamAbbr": "SAS",
        "position": "PF/C",
        "rarity": "legend",
        "ovr": 93,
        "pts": 22.4,
        "reb": 11.8,
        "ast": 3.5,
        "nbaId": 1495,
        "quote": "Twin Towers - Interior defensive fortress and San Antonio's championship foundation."
    },
    {
        "id": "duo-nash-amare",
        "name": "Nash & Amare",
        "subtitle": "Seven Seconds or Less",
        "team": "Phoenix Suns",
        "teamAbbr": "PHX",
        "position": "PG/PF",
        "rarity": "franchise",
        "ovr": 91,
        "pts": 18.8,
        "reb": 8.9,
        "ast": 11.2,
        "nbaId": 959,
        "quote": "Seven Seconds or Less - High-octane offense and pick-and-roll fireworks in Phoenix."
    },
    {
        "id": "duo-payton-kemp",
        "name": "Payton & Kemp",
        "subtitle": "Sonic Boom",
        "team": "Seattle SuperSonics",
        "teamAbbr": "OKC",
        "position": "PG/PF",
        "rarity": "franchise",
        "ovr": 90,
        "pts": 19.6,
        "reb": 8.4,
        "ast": 8.8,
        "nbaId": 56,
        "quote": "Sonic Boom - The Glove's lockdown defense meets Reign Man's ferocious dunks."
    },
    {
        "id": "duo-pierce-garnett",
        "name": "Pierce & Garnett",
        "subtitle": "Celtics Revival",
        "team": "Boston Celtics",
        "teamAbbr": "BOS",
        "position": "SF/PF",
        "rarity": "legend",
        "ovr": 92,
        "pts": 22.8,
        "reb": 8.5,
        "ast": 4.8,
        "nbaId": 1718,
        "quote": "Celtics Revival - Anything is possible! Unyielding intensity and 2008 banner 17."
    },
    {
        "id": "duo-kobe-pau",
        "name": "Kobe & Pau Gasol",
        "subtitle": "Lakers Redemption",
        "team": "Los Angeles Lakers",
        "teamAbbr": "LAL",
        "position": "SG/PF",
        "rarity": "legend",
        "ovr": 93,
        "pts": 27.2,
        "reb": 8.8,
        "ast": 5.2,
        "nbaId": 977,
        "quote": "Lakers Redemption - Seamless triangle offense mastery and back-to-back NBA titles."
    },
    {
        "id": "duo-giannis-middleton",
        "name": "Giannis & Khris Middleton",
        "subtitle": "Bucks Backbone",
        "team": "Milwaukee Bucks",
        "teamAbbr": "MIL",
        "position": "PF/SF",
        "rarity": "franchise",
        "ovr": 91,
        "pts": 28.5,
        "reb": 10.5,
        "ast": 5.8,
        "nbaId": 203507,
        "quote": "Bucks Backbone - Dominant rim pressure paired with smooth mid-range scoring."
    },
    {
        "id": "duo-drj-moses",
        "name": "Dr. J & Moses Malone",
        "subtitle": "76ers Champions",
        "team": "Philadelphia 76ers",
        "teamAbbr": "PHI",
        "position": "SF/C",
        "rarity": "legend",
        "ovr": 92,
        "pts": 24.5,
        "reb": 11.2,
        "ast": 4.2,
        "nbaId": 76681,
        "quote": "76ers Champions - Fo', Fo', Fo'! Airborne artistry combined with board dominance."
    },
    {
        "id": "duo-westbrook-harden",
        "name": "Westbrook & Harden",
        "subtitle": "OKC Backcourt",
        "team": "Oklahoma City Thunder",
        "teamAbbr": "OKC",
        "position": "PG/SG",
        "rarity": "allstar",
        "ovr": 89,
        "pts": 22.4,
        "reb": 6.8,
        "ast": 7.8,
        "nbaId": 201566,
        "quote": "OKC Backcourt - Fearless drives and dynamic playmaking from thunderous young MVPs."
    },
    {
        "id": "duo-duncan-ginobili",
        "name": "Duncan & Ginobili",
        "subtitle": "Spurs Two-Man Game",
        "team": "San Antonio Spurs",
        "teamAbbr": "SAS",
        "position": "PF/SG",
        "rarity": "franchise",
        "ovr": 91,
        "pts": 21.2,
        "reb": 8.2,
        "ast": 5.5,
        "nbaId": 1938,
        "quote": "Spurs Two-Man Game - Fundamental perfection and Euro-step wizardry."
    },
    {
        "id": "duo-lebron-ad",
        "name": "LeBron & AD",
        "subtitle": "Lakers 2020 Title Duo",
        "team": "Los Angeles Lakers",
        "teamAbbr": "LAL",
        "position": "SF/PF",
        "rarity": "franchise",
        "ovr": 93,
        "pts": 26.5,
        "reb": 9.8,
        "ast": 7.8,
        "nbaId": 203076,
        "quote": "Lakers 2020 Title Duo - Dominant interior defense and playmaking in the Orlando Bubble."
    },
    {
        "id": "duo-wade-bosh",
        "name": "Wade & Bosh",
        "subtitle": "Heat Championship Duo",
        "team": "Miami Heat",
        "teamAbbr": "MIA",
        "position": "SG/PF",
        "rarity": "allstar",
        "ovr": 90,
        "pts": 22.1,
        "reb": 7.2,
        "ast": 5.1,
        "nbaId": 2548,
        "quote": "Heat Championship Duo - Flash's slashing and Bosh's key defensive versatility."
    }
]

xfactor_cards = [
    {
        "id": "xfactor-draymond-green",
        "name": "Draymond Green",
        "subtitle": "Defensive Anchor",
        "team": "Golden State Warriors",
        "teamAbbr": "GSW",
        "position": "PF",
        "rarity": "allstar",
        "ovr": 89,
        "pts": 9.5,
        "reb": 8.2,
        "ast": 7.8,
        "nbaId": 203110,
        "quote": "Defensive Anchor - Floor general, defensive genius, and heartbeat of the Warriors dynasty."
    },
    {
        "id": "xfactor-marc-gasol",
        "name": "Marc Gasol",
        "subtitle": "Grizzlies Anchor",
        "team": "Memphis Grizzlies",
        "teamAbbr": "MEM",
        "position": "C",
        "rarity": "starter",
        "ovr": 86,
        "pts": 14.8,
        "reb": 7.8,
        "ast": 4.2,
        "nbaId": 201188,
        "quote": "Grizzlies Anchor - High-IQ passing, DPOY rim protection, and Grit 'n' Grind cornerstone."
    },
    {
        "id": "xfactor-bruce-bowen",
        "name": "Bruce Bowen",
        "subtitle": "Shutdown Specialist",
        "team": "San Antonio Spurs",
        "teamAbbr": "SAS",
        "position": "SF",
        "rarity": "bench",
        "ovr": 82,
        "pts": 8.2,
        "reb": 3.2,
        "ast": 1.8,
        "nbaId": 1477,
        "quote": "Shutdown Specialist - 8x All-Defensive perimeter lock and corner 3 specialist."
    },
    {
        "id": "xfactor-shane-battier",
        "name": "Shane Battier",
        "subtitle": "No-Stats All-Star",
        "team": "Miami Heat",
        "teamAbbr": "MIA",
        "position": "SF",
        "rarity": "bench",
        "ovr": 81,
        "pts": 8.6,
        "reb": 4.1,
        "ast": 2.2,
        "nbaId": 2203,
        "quote": "No-Stats All-Star - Master of charges, analytics, and clutch Finals 3-pointers."
    },
    {
        "id": "xfactor-metta-world-peace",
        "name": "Metta World Peace",
        "subtitle": "Enforcer",
        "team": "Los Angeles Lakers",
        "teamAbbr": "LAL",
        "position": "SF",
        "rarity": "starter",
        "ovr": 85,
        "pts": 13.2,
        "reb": 5.1,
        "ast": 2.8,
        "nbaId": 1897,
        "quote": "Enforcer - Physical intimidation and game-7 clutch 3-pointer in the 2010 Finals."
    },
    {
        "id": "xfactor-nicolas-batum",
        "name": "Nicolas Batum",
        "subtitle": "Do-It-All Wing",
        "team": "LA Clippers",
        "teamAbbr": "LAC",
        "position": "SF",
        "rarity": "bench",
        "ovr": 80,
        "pts": 9.8,
        "reb": 5.2,
        "ast": 4.0,
        "nbaId": 201587,
        "quote": "Do-It-All Wing - Versatile playmaking, deflections, and Swiss-army-knife wing play."
    },
    {
        "id": "xfactor-derrick-white",
        "name": "Derrick White",
        "subtitle": "Two-Way Glue",
        "team": "Boston Celtics",
        "teamAbbr": "BOS",
        "position": "PG",
        "rarity": "starter",
        "ovr": 84,
        "pts": 15.2,
        "reb": 4.2,
        "ast": 5.2,
        "nbaId": 1628401,
        "quote": "Two-Way Glue - Uncanny shot blocking from the guard spot and clutch playmaking."
    },
    {
        "id": "xfactor-danny-green",
        "name": "Danny Green",
        "subtitle": "3-and-D Champion",
        "team": "San Antonio Spurs",
        "teamAbbr": "SAS",
        "position": "SG",
        "rarity": "bench",
        "ovr": 83,
        "pts": 10.5,
        "reb": 3.8,
        "ast": 2.0,
        "nbaId": 201980,
        "quote": "3-and-D Champion - 3x NBA champion wing with transition block genius and 3PT precision."
    },
    {
        "id": "xfactor-kyle-lowry",
        "name": "Kyle Lowry",
        "subtitle": "Toronto Heart",
        "team": "Toronto Raptors",
        "teamAbbr": "TOR",
        "position": "PG",
        "rarity": "starter",
        "ovr": 87,
        "pts": 17.8,
        "reb": 4.8,
        "ast": 7.5,
        "nbaId": 200768,
        "quote": "Toronto Heart - Charge-taking tenacity, leadership, and 2019 championship heart."
    },
    {
        "id": "xfactor-pj-tucker",
        "name": "P.J. Tucker",
        "subtitle": "Playoff Warrior",
        "team": "Milwaukee Bucks",
        "teamAbbr": "MIL",
        "position": "PF",
        "rarity": "bench",
        "ovr": 79,
        "pts": 6.2,
        "reb": 5.8,
        "ast": 1.2,
        "nbaId": 200782,
        "quote": "Playoff Warrior - Relentless offensive rebounding, corner 3s, and star-dogging defense."
    },
    {
        "id": "xfactor-tony-allen",
        "name": "Tony Allen",
        "subtitle": "The Grindfather",
        "team": "Memphis Grizzlies",
        "teamAbbr": "MEM",
        "position": "SG",
        "rarity": "bench",
        "ovr": 83,
        "pts": 8.9,
        "reb": 4.2,
        "ast": 1.8,
        "nbaId": 2754,
        "quote": "The Grindfather - 'First Team All-Defense' legend who defined Memphis Grit 'n' Grind."
    },
    {
        "id": "xfactor-ben-wallace",
        "name": "Ben Wallace",
        "subtitle": "Rebounding Anchor",
        "team": "Detroit Pistons",
        "teamAbbr": "DET",
        "position": "C",
        "rarity": "allstar",
        "ovr": 87,
        "pts": 7.3,
        "reb": 13.0,
        "ast": 1.8,
        "nbaId": 1112,
        "quote": "Rebounding Anchor - Undrafted 4x DPOY powerhouse who anchored Detroit's 2004 defense."
    },
    {
        "id": "xfactor-josh-hart",
        "name": "Josh Hart",
        "subtitle": "Glue Guy",
        "team": "New York Knicks",
        "teamAbbr": "NYK",
        "position": "SG",
        "rarity": "bench",
        "ovr": 80,
        "pts": 10.2,
        "reb": 8.3,
        "ast": 4.1,
        "nbaId": 1628404,
        "quote": "Glue Guy - Non-stop hustle, elite rebounding for a guard, and 48-minute endurance."
    },
    {
        "id": "xfactor-og-anunoby",
        "name": "OG Anunoby",
        "subtitle": "Lockdown Wing",
        "team": "New York Knicks",
        "teamAbbr": "NYK",
        "position": "SF",
        "rarity": "bench",
        "ovr": 83,
        "pts": 15.1,
        "reb": 4.6,
        "ast": 2.1,
        "nbaId": 1628384,
        "quote": "Lockdown Wing - Elite physical wing defense and reliable corner 3-point shooting."
    },
    {
        "id": "xfactor-al-horford",
        "name": "Al Horford",
        "subtitle": "Playoff Al",
        "team": "Boston Celtics",
        "teamAbbr": "BOS",
        "position": "C",
        "rarity": "starter",
        "ovr": 85,
        "pts": 12.8,
        "reb": 7.5,
        "ast": 3.8,
        "nbaId": 201143,
        "quote": "Playoff Al - Veteran stretch-5 composure, rim protection, and clutch playoff performances."
    },
    {
        "id": "xfactor-marcus-smart",
        "name": "Marcus Smart",
        "subtitle": "Heart & Hustle",
        "team": "Boston Celtics",
        "teamAbbr": "BOS",
        "position": "PG",
        "rarity": "starter",
        "ovr": 84,
        "pts": 13.1,
        "reb": 3.8,
        "ast": 5.9,
        "nbaId": 203935,
        "quote": "Heart & Hustle - 2022 DPOY guard whose diving loose-ball effort set Boston's culture."
    },
    {
        "id": "xfactor-andre-iguodala",
        "name": "Andre Iguodala",
        "subtitle": "Finals Difference-Maker",
        "team": "Golden State Warriors",
        "teamAbbr": "GSW",
        "position": "SF",
        "rarity": "starter",
        "ovr": 86,
        "pts": 11.4,
        "reb": 5.2,
        "ast": 4.8,
        "nbaId": 2738,
        "quote": "Finals Difference-Maker - 2015 Finals MVP whose strip-steals and IQ secured 4 titles."
    },
    {
        "id": "xfactor-jrue-holiday",
        "name": "Jrue Holiday",
        "subtitle": "Two-Way Guard",
        "team": "Boston Celtics",
        "teamAbbr": "BOS",
        "position": "PG",
        "rarity": "allstar",
        "ovr": 87,
        "pts": 15.8,
        "reb": 4.8,
        "ast": 6.1,
        "nbaId": 201950,
        "quote": "Two-Way Guard - Ultimate guard defender and champion key for both Bucks and Celtics."
    },
    {
        "id": "xfactor-michael-cooper",
        "name": "Michael Cooper",
        "subtitle": "Defensive Specialist",
        "team": "Los Angeles Lakers",
        "teamAbbr": "LAL",
        "position": "SG",
        "rarity": "bench",
        "ovr": 81,
        "pts": 8.9,
        "reb": 3.2,
        "ast": 4.2,
        "nbaId": 76442,
        "quote": "Defensive Specialist - 1987 DPOY perimeter stopper Larry Bird called his toughest defender."
    },
    {
        "id": "xfactor-avery-bradley",
        "name": "Avery Bradley",
        "subtitle": "Perimeter Lockdown",
        "team": "Boston Celtics",
        "teamAbbr": "BOS",
        "position": "SG",
        "rarity": "bench",
        "ovr": 78,
        "pts": 11.2,
        "reb": 3.1,
        "ast": 1.8,
        "nbaId": 202340,
        "quote": "Perimeter Lockdown - Full-court pressure point guard pest with quick hands."
    }
]

file_lines = [
    'import { Card } from "../types";',
    '',
    'export const DUO_AND_XFACTOR_CARDS: Card[] = ['
]

# Process Duo
for c in duo_cards:
    img = f"https://cdn.nba.com/headshots/nba/latest/1040x760/{c['nbaId']}.png" if c['nbaId'] else "https://cdn.nba.com/headshots/nba/latest/1040x760/fallback.png"
    card_str = f"""  {{
    id: "{c['id']}",
    number: 0,
    name: "{c['name']}",
    team: "{c['team']}",
    teamAbbr: "{c['teamAbbr']}",
    teamColor: "#333",
    position: "{c['position']}",
    rarity: "{c['rarity']}" as const,
    category: "Duo" as const,
    subtitle: "{c['subtitle']}",
    series: "Dynamic Duo Series",
    isHistorical: true,
    pts: {c['pts']},
    reb: {c['reb']},
    ast: {c['ast']},
    nbaId: {c['nbaId']},
    imageUrl: "{img}",
    stats: {{
      points: {c['pts']},
      rebounds: {c['reb']},
      assists: {c['ast']},
      ovr: {c['ovr']}
    }},
    description: "{c['quote']}",
    quote: "{c['quote']}"
  }},"""
    file_lines.append(card_str)

# Process X-Factor
for c in xfactor_cards:
    img = f"https://cdn.nba.com/headshots/nba/latest/1040x760/{c['nbaId']}.png" if c['nbaId'] else "https://cdn.nba.com/headshots/nba/latest/1040x760/fallback.png"
    card_str = f"""  {{
    id: "{c['id']}",
    number: 0,
    name: "{c['name']}",
    team: "{c['team']}",
    teamAbbr: "{c['teamAbbr']}",
    teamColor: "#333",
    position: "{c['position']}",
    rarity: "{c['rarity']}" as const,
    category: "X-Factor" as const,
    subtitle: "{c['subtitle']}",
    series: "X-Factor Series",
    isHistorical: true,
    pts: {c['pts']},
    reb: {c['reb']},
    ast: {c['ast']},
    nbaId: {c['nbaId']},
    imageUrl: "{img}",
    stats: {{
      points: {c['pts']},
      rebounds: {c['reb']},
      assists: {c['ast']},
      ovr: {c['ovr']}
    }},
    description: "{c['quote']}",
    quote: "{c['quote']}"
  }},"""
    file_lines.append(card_str)

file_lines.append('];')

with open("src/data/duoAndXFactorCards.ts", "w") as f:
    f.write("\n".join(file_lines))

print("Regenerated src/data/duoAndXFactorCards.ts with quote property!")
